---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "Marcin Kuthan"
- git config --global user.email "marcin.kuthan@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
script:
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="mkuthan/mkuthan.github.io"
  - secure: "Ij1p8qkICse/j/zuj0XDlt1OZr4mly0QBA1wT9F1xIbJEt8XX90zryC1RaHh/gjTRCacIIv8SEkx6XmXynew7yoU1FvVR03ZGj7y15pHXJuLY3H4yzkV3rkWctnId+nhyu+tVdH/sixMqF349oW/po/UakiG0oieaoqIpTif+Jc="
