name: Algolia

on:
  push:
    branches:
      - master

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dieghernan/algolia-jekyll-action@v2
        with:
          ruby-version: '2.7'
          APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'
